# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedTech',
            fields=[
                ('tech_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.Tech')),
            ],
            bases=('board.tech',),
        ),
        migrations.CreateModel(
            name='RequiredTech',
            fields=[
                ('tech_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.Tech')),
            ],
            bases=('board.tech',),
        ),
        migrations.AddField(
            model_name='profile',
            name='excluded_techs',
            field=models.ManyToManyField(to='board.ExcludedTech'),
        ),
        migrations.AddField(
            model_name='profile',
            name='required_techs',
            field=models.ManyToManyField(to='board.RequiredTech'),
        ),
    ]
